name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
      # 👇 v4 usa google-github-actions, non più googleapis
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
